### ISSUE TITLE
Integration of other frontend modules into the sitemap

### ISSUE THREAD

**Issue by JohnnyMcWeed** [cebe/luya-module-sitemap#15]
It would be nice to have a way to integrate other modules into the sitemap.
E.g. if the news module should be included.

Could be something like this:
- the sitemap module checks through all modules whether a method is implemented or not.
- this method returns the url's for the sitemap which are included then

**Comment by nadar** [comment]
@JohnnyMcWeed yes indeed, this could be interesting for structure data of CRUD tables, for example news. Instead of checking for methods we could introduce an SitemapLinkInterface which can be implemented, afterwards you could tell the sitemap module where to lookup for those classes with a config property (like `$linkInterfaceLookup = ['luya\crawler\Link']`. The SitemapLinkInterface would require 2 methods:

+ iteratorLinks(): An iteration of links which must return a SitemapLinkInterface (could be used to run the find() method)
+ linkGetUrl(): The method which returns the link itself. (would be returned by the object itself)

Maybe it would be even better to have two interfaces: SitemapLinkIterationInterface and SitemapLinkItemInterface as by definition the implemented class must not provide both functions.

The most interesting use case could be: https://github.com/luyadev/luya-module-crawler Because the crawler already knows all the links of the website but it can not communicate to the sitemap module, with this solution it would be possible.

If this could be an acceptable solution, i would draft the interfaces.

**Comment by rochdi80tn** [comment]
Hi @nadar,
I am interested in implementing this feature. 
Could you please share the drafted interfaces (if available)?

**Comment by rochdi80tn** [comment]
Just following your suggestion above, this would be the interface..

```php

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

namespace cebe\luya\sitemap;

/**
 * Description of SitemapLinkInterface
 *
 * @author Rochdi Bazine
 * @since 1.2.1?
 */
interface SitemapLinkInterface
{
    /**
     * Return an iteration of links. If used in ngRestModel, could be useful 
     * to run the find() method
     * @return SitemapLinkInterface.
     */
    public function iteratorLinks();

    /**
     * @return array Full URL of the link as first entry and the last
     * modification timestamp as second entry
     */
    public function linkGetUrl();
}

```

**Comment by rochdi80tn** [comment]
And an implemetation might be on a `News` model  like this

``` php
    /**
    * @inheritdoc 
    */
    public function iteratorLinks(){
        return self::find()->publishedOnly()->nonExpired()->all();                
    }

    /**
     * @inheritdoc 
     */
    public function linkGetUrl(){
        $absoluteBaseUrl = Url::base(true);
        return [
            $absoluteBaseUrl. Url::toModuleRoute('mymodulefrontend', ['/mymodulefrontend/news/view', 'id' => $this->id]),
            $this->updated_at
        ];
    }

```

**Comment by rochdi80tn** [comment]
Suggested implementation in PR https://github.com/cebe/luya-module-sitemap/pull/22
